[package]
name = "mow-grep"
version = "0.1.0"
authors = ["ratnick"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "^0"
